// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcABxEajPHpW9ibTPfm4a1oEwW8HRD6TU',
    appId: '1:870128464598:web:1cae27ef13e086608dcf77',
    messagingSenderId: '870128464598',
    projectId: 'chat-app-e06c8',
    authDomain: 'chat-app-e06c8.firebaseapp.com',
    storageBucket: 'chat-app-e06c8.appspot.com',
    measurementId: 'G-8G3MZBW6S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyr2cNXZuBuwOR21vpbQTSpCxDCYSQ-AM',
    appId: '1:870128464598:android:c9d3c43c6f4329d48dcf77',
    messagingSenderId: '870128464598',
    projectId: 'chat-app-e06c8',
    storageBucket: 'chat-app-e06c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaFbmso3rA6JeSTgJNS4z2mwy9e6nlKQ',
    appId: '1:870128464598:ios:4f1a64ef91bd52dc8dcf77',
    messagingSenderId: '870128464598',
    projectId: 'chat-app-e06c8',
    storageBucket: 'chat-app-e06c8.appspot.com',
    iosBundleId: 'com.example.chatApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApaFbmso3rA6JeSTgJNS4z2mwy9e6nlKQ',
    appId: '1:870128464598:ios:f67463428d2db01d8dcf77',
    messagingSenderId: '870128464598',
    projectId: 'chat-app-e06c8',
    storageBucket: 'chat-app-e06c8.appspot.com',
    iosBundleId: 'com.example.chatApp2.RunnerTests',
  );
}
